- name: variables
  hosts: local
  connection: local
  vars: 
    GREET: "PLAY"
  vars_file:
    - course.yaml
  vars_prompt:
    - name: GREET
      prompt: Enter the value
      private: false
  tasks:
    - name: print the variable
      vars: 
        GREET: "Task"
      ansible.builtin.debug:
        msg: "Hello From {{GREET}}"